### ISSUE TITLE
initStation ignored on play notification

### ISSUE THREAD

**Issue by lxne** [Tom-Hirschberger/MMM-MplayerRadio#15]
First thing – I love this module.

One issue: initStation seems to be not working correctly.
If I set an integer the correct station is highlighted on MagicMirror start, but when I send the RADIO_PLAY notification instead of playing the initStation the first station gets highlighted and is being played.

Am I missing something?

I am using vlc to play the stations.
System: Most recent Buster, most recent MM, most recent MMM-MplayerRadio

**Comment by Tom-Hirschberger** [comment]
Hi,

I am really happy that so much people use my module.
My mirror currently is am mess because I upgraded to bullseye and tried a lot of things.
I checked the code and I think I found the line where the problem occurs but it will take me a few days to test the changes. 
Can you answer me a few questions?

Do you use any kind of profile module?
How do you send the play notification? Is the payload empty?
Does the problem occur if you send an RADIO_TOGGLE instead of the RADIO_PLAY notification?

**Comment by lxne** [comment]
Off course I can.

_Do you use any kind of profile module?_
No profile module, only MMM-pages.

_How do you send the play notification? Is the payload empty?_
I send it via MMM-GoogleAssistant or MMM-TelegramBot.
`/notification RADIO_PLAY`
Yes, payload is empty.

_Does the problem occur if you send an RADIO_TOGGLE instead of the RADIO_PLAY notification?_
If I send RADIO_TOGGLE it works. Station does not change. And when I stop it with RADIO_TOGGLE and then start it with RADIO_PLAY station doesn't change either. But if I use RADIO_PLAY after MM starts up the change happens.

Hope this is helpful.

**Comment by Tom-Hirschberger** [comment]
Hi,

perfect. Your information rellay helps me and supports my theory.
Only a small change should be needed.

**Comment by Tom-Hirschberger** [comment]
Just released the new version 0.0.8 which should fix the problem. Can you please verify that it is working now and give me feedback.

**Comment by lxne** [comment]
Works. No issues so far.
Thank you very much.

Und einen guten Rutsch!
